# Generated by Django 3.2.3 on 2022-05-16 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remedios', '0004_alter_remedios_thumbnail'),
        ('orden', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='mercadopago_token',
            new_name='stripe_token',
        ),
        migrations.AlterField(
            model_name='remedioordenado',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orden.orden'),
        ),
        migrations.AlterField(
            model_name='remedioordenado',
            name='remedio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='remedios.remedios'),
        ),
    ]
