# Generated by Django 3.2.3 on 2022-05-12 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remedios', '0002_auto_20220512_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedios',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='remedios.marcaremedio'),
        ),
    ]
